### ISSUE TITLE
Q: Why all the commit messages are empty?

### ISSUE THREAD

**Issue by tovbinm** [metamatex/metamate#41]
It makes it impossible to understand why certain changes are done etc.

**Comment by ppwfx** [comment]
Hey @tovbinm,

it's just a bad habit. There weren't many external people looking at the commit history so far, so it wasn't really necessary. We'll have proper commit messages from now on. 

Sorry for the inconvenience.

Do you have more questions I can help you with?

**Comment by tovbinm** [comment]
Thank you! That would be great.

I was wondering what are your plans for this project? How is it being used right now, i.e. for a side project or some project at work?

**Comment by ppwfx** [comment]
We want to give developers full programmatic access to all kinds of network-connected data sources eventually. Similar to what the semantic web tries to achieve, just in a simpler way with tools developers already know. Our current focus lies in giving simple access to data of the social domain. HackerNews, ActivityPub, Reddit, stuff like that.

We are looking for like-minded people to grow a community around this technology.

MetaMate doesn't power any application yet (as far as we know), but we are getting started with an alternative HN client that's getting its data from a MetaMate instance.

**Comment by ppwfx** [comment]
Hey @tovbinm 

Did that answer your question?

**Comment by tovbinm** [comment]
Yes, thank you.
